FROM node:8 AS base
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "./"]

FROM base AS prod
EXPOSE 3001
COPY ["server/", "./server/"]
COPY ["dist/", "./dist/"]
RUN npm install --production --silent
CMD npm run server