version: '3.4'

services:
  server:
    image: platzi-badge:dev
    build: 
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    ports:
      - ${PORT}:${PORT}
      - ${SERVER_PORT}:3001
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules