version: '3.4'

services:
  platzi-badge:
    image: platzi-badge-prod
    build: 
      context: .
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001