version: '3.4'

services:
  platzi-badge:
    image: platzi-badge
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 3001:3001
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules